import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/hooks/useAuth';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { supabase } from '@/integrations/supabase/client';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ArrowLeft, 
  Download, 
  Brain,
  Lightbulb,
  CheckCircle,
  AlertTriangle,
  Clock
} from 'lucide-react';
import { ScoreCircle } from '@/components/ScoreCircle';
import { AICoachPanel } from '@/components/AICoachPanel';
import { PracticeTaskPanel } from '@/components/PracticeTaskPanel';
import { toast } from 'sonner';
import jsPDF from 'jspdf';

interface TestResult {
  id: string;
  speech_mode: string;
  audience_type: string;
  duration_seconds: number;
  flow_continuity_score: number | null;
  pause_control_score: number | null;
  vocal_confidence_score: number | null;
  visual_confidence_score: number | null;
  overall_score: number | null;
  audio_analysis: any;
  video_analysis: any;
  insights: any[];
  timeline_data: any[];
  created_at: string;
}

export default function TestResults() {
  const { id } = useParams<{ id: string }>();
  const { user, loading: authLoading } = useAuth();
  const navigate = useNavigate();
  const [test, setTest] = useState<TestResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [showCoach, setShowCoach] = useState(false);

  useEffect(() => {
    if (!authLoading && !user) {
      navigate('/login');
    }
  }, [user, authLoading, navigate]);

  useEffect(() => {
    if (user && id) {
      fetchTestResult();
    }
  }, [user, id]);

  const fetchTestResult = async () => {
    const { data, error } = await supabase
      .from('speech_tests')
      .select('*')
      .eq('id', id)
      .eq('user_id', user!.id)
      .maybeSingle();

    if (error || !data) {
      toast.error('Test not found');
      navigate('/dashboard');
      return;
    }

    setTest(data as TestResult);
    setLoading(false);
  };

  const formatMode = (mode: string) => {
    const modes: Record<string, string> = {
      academic: 'Academic',
      startup_pitch: 'Startup Pitch',
      debate_mun: 'Debate/MUN'
    };
    return modes[mode] || mode;
  };

  const formatAudience = (audience: string) => {
    const audiences: Record<string, string> = {
      neutral: 'Neutral',
      supportive: 'Supportive',
      critical: 'Critical'
    };
    return audiences[audience] || audience;
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const downloadReport = () => {
    if (!test) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFillColor(13, 13, 15);
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 107, 71);
    doc.setFontSize(24);
    doc.text('ORATORA', 20, 25);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.text('Speaking Analysis Report', 20, 35);
    
    // Content
    doc.setTextColor(0, 0, 0);
    
    // Test info
    doc.setFontSize(14);
    doc.text(`Test Date: ${formatDate(test.created_at)}`, 20, 55);
    doc.text(`Mode: ${formatMode(test.speech_mode)}`, 20, 65);
    doc.text(`Duration: ${test.duration_seconds}s`, 20, 75);
    
    // Scores
    doc.setFontSize(18);
    doc.text('Scores', 20, 95);
    
    doc.setFontSize(12);
    doc.text(`Overall Score: ${test.overall_score}/100`, 20, 110);
    doc.text(`Flow Continuity: ${test.flow_continuity_score}/100`, 20, 120);
    doc.text(`Pause Control: ${test.pause_control_score}/100`, 20, 130);
    doc.text(`Vocal Confidence: ${test.vocal_confidence_score}/100`, 20, 140);
    doc.text(`Visual Confidence: ${test.visual_confidence_score}/100`, 20, 150);
    
    // Insights
    doc.setFontSize(18);
    doc.text('Key Insights', 20, 175);
    
    let yPos = 190;
    doc.setFontSize(11);
    
    (test.insights || []).slice(0, 3).forEach((insight: any, index: number) => {
      doc.text(`${index + 1}. ${insight.title}: ${insight.message}`, 20, yPos, { maxWidth: pageWidth - 40 });
      yPos += 20;
    });
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by ORATORA - Master the pause. Control the room.', 20, 280);
    
    doc.save(`oratora-report-${test.id.slice(0, 8)}.pdf`);
    toast.success('Report downloaded!');
  };

  if (loading || authLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!test) return null;

  const scores = [
    { label: 'Flow Continuity', score: test.flow_continuity_score || 0 },
    { label: 'Pause Control', score: test.pause_control_score || 0 },
    { label: 'Vocal Confidence', score: test.vocal_confidence_score || 0 },
    { label: 'Visual Confidence', score: test.visual_confidence_score || 0 },
  ];

  const timeline = test.timeline_data || [];
  const insights = test.insights || [];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      
      <main className="flex-1 pt-24 pb-12">
        <div className="container mx-auto px-4">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 mb-8"
          >
            <div>
              <Link 
                to="/dashboard" 
                className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-4"
              >
                <ArrowLeft className="w-4 h-4" />
                Back to Dashboard
              </Link>
              <h1 className="font-display text-3xl font-bold">
                {formatMode(test.speech_mode)} Analysis
              </h1>
              <div className="flex items-center gap-4 text-muted-foreground mt-2">
                <span className="flex items-center gap-1">
                  <Clock className="w-4 h-4" />
                  {test.duration_seconds}s
                </span>
                <span>•</span>
                <span>{formatAudience(test.audience_type)} audience</span>
                <span>•</span>
                <span>{formatDate(test.created_at)}</span>
              </div>
            </div>
            
            <div className="flex gap-3">
              <Button 
                variant={showCoach ? "default" : "outline"} 
                onClick={() => setShowCoach(!showCoach)}
              >
                <Brain className="w-4 h-4" />
                {showCoach ? 'Hide Coach' : 'AI Coach'}
              </Button>
              <Button variant="outline" onClick={downloadReport}>
                <Download className="w-4 h-4" />
                Download Report
              </Button>
            </div>
          </motion.div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Main Content */}
            <div className="lg:col-span-2 space-y-6">
              {/* Overall Score */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="glass-card p-8"
              >
                <div className="flex flex-col md:flex-row items-center gap-8">
                  <ScoreCircle score={test.overall_score || 0} label="Overall Score" size="lg" />
                  
                  <div className="flex-1 grid grid-cols-2 gap-4">
                    {scores.map((item, index) => (
                      <div key={item.label} className="text-center p-4 bg-secondary/30 rounded-xl">
                        <div className="text-2xl font-display font-bold mb-1">
                          {item.score}
                        </div>
                        <div className="text-xs text-muted-foreground">{item.label}</div>
                      </div>
                    ))}
                  </div>
                </div>
              </motion.div>

              {/* AI Coach Panel - Shows when toggled */}
              <AnimatePresence>
                {showCoach && (
                  <AICoachPanel
                    testData={{
                      flow_continuity_score: test.flow_continuity_score,
                      pause_control_score: test.pause_control_score,
                      vocal_confidence_score: test.vocal_confidence_score,
                      visual_confidence_score: test.visual_confidence_score,
                      timeline_data: test.timeline_data || [],
                      audio_analysis: test.audio_analysis,
                      video_analysis: test.video_analysis,
                      duration_seconds: test.duration_seconds,
                    }}
                    onClose={() => setShowCoach(false)}
                  />
                )}
              </AnimatePresence>

              {/* Practice Task Panel - Always visible */}
              <PracticeTaskPanel
                testData={{
                  flow_continuity_score: test.flow_continuity_score,
                  pause_control_score: test.pause_control_score,
                  vocal_confidence_score: test.vocal_confidence_score,
                  visual_confidence_score: test.visual_confidence_score,
                }}
                onPracticeComplete={() => navigate('/speaking-test')}
              />

              {/* Timeline */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="glass-card p-6"
              >
                <h3 className="font-display font-semibold text-lg mb-4">Speech Flow Timeline</h3>
                
                <div className="flex items-center gap-4 mb-4 text-sm">
                  <span className="flex items-center gap-2">
                    <span className="w-4 h-4 rounded segment-smooth" /> Smooth Flow
                  </span>
                  <span className="flex items-center gap-2">
                    <span className="w-4 h-4 rounded segment-natural" /> Natural Pause
                  </span>
                  <span className="flex items-center gap-2">
                    <span className="w-4 h-4 rounded segment-awkward" /> Awkward Silence
                  </span>
                </div>

                <div className="h-12 rounded-lg overflow-hidden flex">
                  {timeline.map((segment: any, index: number) => (
                    <motion.div
                      key={index}
                      initial={{ scaleX: 0 }}
                      animate={{ scaleX: 1 }}
                      transition={{ duration: 0.3, delay: index * 0.05 }}
                      className={`segment-${segment.type} flex-1`}
                      title={`${Math.round(segment.start)}s - ${Math.round(segment.end)}s: ${segment.type}`}
                    />
                  ))}
                </div>

                <div className="flex justify-between text-sm text-muted-foreground mt-2">
                  <span>0:00</span>
                  <span>Intro</span>
                  <span>Body</span>
                  <span>Conclusion</span>
                  <span>{Math.floor(test.duration_seconds / 60)}:{(test.duration_seconds % 60).toString().padStart(2, '0')}</span>
                </div>
              </motion.div>

              {/* Insights */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="glass-card p-6"
              >
                <h3 className="font-display font-semibold text-lg mb-4">Key Insights</h3>
                
                <div className="space-y-4">
                  {insights.map((insight: any, index: number) => (
                    <div 
                      key={index}
                      className={`p-4 rounded-xl border ${
                        insight.type === 'strength' 
                          ? 'bg-oratora-success/10 border-oratora-success/30' 
                          : insight.type === 'improvement'
                          ? 'bg-oratora-warning/10 border-oratora-warning/30'
                          : 'bg-oratora-info/10 border-oratora-info/30'
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        {insight.type === 'strength' ? (
                          <CheckCircle className="w-5 h-5 text-oratora-success flex-shrink-0 mt-0.5" />
                        ) : insight.type === 'improvement' ? (
                          <AlertTriangle className="w-5 h-5 text-oratora-warning flex-shrink-0 mt-0.5" />
                        ) : (
                          <Lightbulb className="w-5 h-5 text-oratora-info flex-shrink-0 mt-0.5" />
                        )}
                        <div>
                          <h4 className="font-semibold mb-1">{insight.title}</h4>
                          <p className="text-sm text-muted-foreground">{insight.message}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              {/* Audio Analysis */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="glass-card p-6"
              >
                <h3 className="font-display font-semibold mb-4">Audio Analysis</h3>
                
                <div className="space-y-4">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Words per Minute</span>
                    <span className="font-semibold">{test.audio_analysis?.wordsPerMinute || 'N/A'}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Filler Words</span>
                    <span className="font-semibold">{test.audio_analysis?.fillerWordCount || 0}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Silence %</span>
                    <span className="font-semibold">{test.audio_analysis?.silencePercentage || 0}%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Pitch Variance</span>
                    <span className="font-semibold">{test.audio_analysis?.pitchVariance || 'N/A'}</span>
                  </div>
                </div>
              </motion.div>

              {/* Video Analysis */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
                className="glass-card p-6"
              >
                <h3 className="font-display font-semibold mb-4">Video Analysis</h3>
                
                <div className="space-y-4">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Eye Contact</span>
                    <span className="font-semibold">{test.video_analysis?.eyeContactPercentage || 0}%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Face Presence</span>
                    <span className="font-semibold">{test.video_analysis?.facePresencePercentage || 0}%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Movement Score</span>
                    <span className="font-semibold">{test.video_analysis?.headMovementScore || 0}</span>
                  </div>
                </div>
              </motion.div>

              {/* Quick Actions */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6 }}
                className="glass-card p-6"
              >
                <h3 className="font-display font-semibold mb-4">Next Steps</h3>
                
                <div className="space-y-3">
                  <Link to="/speaking-test" className="block">
                    <Button variant="hero" className="w-full">
                      Take Another Test
                    </Button>
                  </Link>
                  <Link to="/test-history" className="block">
                    <Button variant="outline" className="w-full">
                      View All Tests
                    </Button>
                  </Link>
                  <Link to="/resources" className="block">
                    <Button variant="ghost" className="w-full">
                      Learning Resources
                    </Button>
                  </Link>
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
